<?php
  if(!isset($_SESSION)){
    session_start();
  }
  if(isset($_SESSION['id'])){
    header('location:adm_paginas.php');
  }else{
    session_destroy();
    header('location:../login.php');
  }
 ?>
